# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_install:
  - Rscript -e 'source("https://bioconductor.org/biocLite.R", ask = FALSE);biocLite(c("multtest"))'
